#!/usr/bin/env python

import sys

import morfessor
import morfessor.evaluation

from morfessor import _logger


def merge_constructions(constructions):
    compound = constructions[0]
    for i in range(1, len(constructions)):
        compound = compound + constructions[i]
    return compound


def main(argv):
    parser = morfessor.get_evaluation_argparser()
    try:
        args = parser.parse_args(argv)
        morfessor.main_evaluation(args)
    except morfessor.ArgumentException as e:
        parser.error(e)
    except Exception as e:
        _logger.error("Fatal Error %s %s" % (type(e), e))
        raise

if __name__ == "__main__":
    main(sys.argv[1:])
