#!/usr/bin/env python

import logging
import sys

import morfessor

def main(argv):
    parser = morfessor.get_evaluation_argparser()
    try:
        args = parser.parse_args(argv)
        morfessor.configure_logger(logging.getLogger(), args)
        morfessor.main_evaluation(args)
    except morfessor.ArgumentException as e:
        parser.error(e)
    except Exception as e:
        logging.error("Fatal Error %s %s" % (type(e), e))
        raise

if __name__ == "__main__":
    main(sys.argv[1:])
